"use client";
import "./static-operations-panel.css";
import { useEffect, useState } from "react";
import { useI18n } from "../i18n/client";
import { PanelHeading } from "./shared-ui";
import { toast } from "./toast";
type Row=Record<string,unknown>;
type Photo={id:string;name:string;status:"uploading"|"uploaded"|"failed";evidenceId?:string;error?:string;file:File};

export default function StaticOperationsPanel(){const {t}=useI18n();const [jobs,setJobs]=useState<Row[]>([]);const [orders,setOrders]=useState<Row[]>([]);const [photos,setPhotos]=useState<Record<string,Photo[]>>({});const [error,setError]=useState("");
 async function load(){const response=await fetch("/api/operations?pageSize=50");if(response.ok){const payload=await response.json();setJobs(payload.jobs);setOrders(payload.workOrders);}}
 useEffect(()=>{void load();},[]);
 async function updateJob(job:Row,status:string){const response=await fetch(`/api/production-jobs/${job.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status,expectedVersion:job.version})});const payload=await response.json();response.ok?(toast.success(t("Production status updated.")),void load()):setError(payload.error);}
 async function uploadPhoto(orderId:string,file:File){const photo={id:crypto.randomUUID(),name:file.name,status:"uploading" as const,file};setPhotos(current=>({...current,[orderId]:[...(current[orderId]??[]),photo]}));const form=new FormData();form.set("file",file);const response=await fetch(`/api/work-orders/${orderId}/evidence`,{method:"POST",body:form});const payload=await response.json();setPhotos(current=>({...current,[orderId]:(current[orderId]??[]).map(item=>item.id===photo.id?response.ok?{...item,status:"uploaded",evidenceId:payload.id}:{...item,status:"failed",error:payload.error}:item)}));}
 async function addPhotos(orderId:string,files:FileList|null){if(files)for(const file of Array.from(files))await uploadPhoto(orderId,file);}
 async function retry(orderId:string,photo:Photo){setPhotos(current=>({...current,[orderId]:(current[orderId]??[]).filter(item=>item.id!==photo.id)}));await uploadPhoto(orderId,photo.file);}
 async function complete(order:Row){const evidenceIds=(photos[String(order.id)]??[]).flatMap(photo=>photo.evidenceId?[photo.evidenceId]:[]);const response=await fetch(`/api/work-orders/${order.id}/complete`,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify({expectedVersion:order.version,evidenceIds,result:"completed",clientShareable:true})});const payload=await response.json();response.ok?(toast.success(t("Installation completed with proof.")),void load()):setError(payload.error);}
 async function exception(order:Row,action:string){const reason=window.prompt(t("Reason and recovery note"))?.trim();if(!reason)return;const response=await fetch(`/api/work-orders/${order.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action,reason,expectedVersion:order.version})});const payload=await response.json();response.ok?(toast.success(t("Work-order exception recorded.")),void load()):setError(payload.error);}
 if(!jobs.length&&!orders.length)return null;return <section className="panel static-operations"><PanelHeading eyebrow={t("Static fulfillment")} title={t("Production and installation queue")}/>{error?<p className="form-error" role="alert">{error}</p>:null}<div className="operations-grid"><section><h3>{t("Production")}</h3>{jobs.map(job=><article key={String(job.id)}><strong>{String(job.inventory_name)}</strong><small>{String(job.campaign_name)} · {t(String(job.status))}</small><label>{t("Next status")}<select value={String(job.status)} onChange={e=>void updateJob(job,e.target.value)}><option value="ready">{t("Ready")}</option><option value="in_production">{t("In production")}</option><option value="printed">{t("Printed")}</option><option value="shipped">{t("Shipped")}</option><option value="delivered">{t("Delivered to installer")}</option><option value="reprint_required">{t("Reprint required")}</option></select></label></article>)}</section><section><h3>{t("Installation work orders")}</h3>{orders.map(order=><article key={String(order.id)}><strong>{String(order.inventory_name)}</strong><small>{String(order.planned_at??t("Date not scheduled"))} · {t(String(order.status))}</small>{order.work_type==="install"?<label className="file-picker">{t("Add completion photos")}<input type="file" accept="image/png,image/jpeg" multiple capture="environment" onChange={e=>void addPhotos(String(order.id),e.target.files)}/></label>:null}{(photos[String(order.id)]??[]).map(photo=><div className="evidence-row" key={photo.id}><span>{photo.name} — {t(photo.status)}</span>{photo.status==="failed"?<button type="button" onClick={()=>void retry(String(order.id),photo)}>{t("Retry")}</button>:null}</div>)}{order.work_type==="removal"?<button className="primary-button" type="button" onClick={()=>void exception(order,"remove")}>{t("Confirm removal")}</button>:<button className="primary-button" type="button" disabled={!(photos[String(order.id)]??[]).some(photo=>photo.status==="uploaded")} onClick={()=>void complete(order)}>{t("Complete installation")}</button>}<div className="exception-actions"><button type="button" onClick={()=>void exception(order,"weather_delay")}>{t("Weather delay")}</button><button type="button" onClick={()=>void exception(order,"access_blocked")}>{t("Access blocked")}</button><button type="button" onClick={()=>void exception(order,"reprint_required")}>{t("Reprint")}</button></div></article>)}</section></div></section>}
